using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using LagersystemLVHome.Data;
using LagersystemLVHome.Domain.Models;

namespace LagersystemLVHome.Application.Services;

public sealed class TamperProofAuditService
{
    private readonly InventoryDbContext _dbContext;
    private readonly ILogger<TamperProofAuditService> _logger;

    public TamperProofAuditService(
        InventoryDbContext dbContext,
        ILogger<TamperProofAuditService> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    /// <summary>
    /// Creates a tamper-proof audit log with a hash based on immutable data.
    /// Hash is computed WITHOUT the ID (since ID is generated by the database sequence).
    /// Timestamp is rounded to seconds (no milliseconds) to avoid PostgreSQL precision mismatches.
    /// </summary>
    public async Task<AuditLog> CreateTamperProofAuditLogAsync(
        int userId,
        string action,
        string? entityType = null,
        int? entityId = null,
        string? changes = null,
        string? ipAddress = null, CancellationToken cancellationToken = default)
    {
        try
        {
            // Round timestamp to seconds (remove milliseconds).
            // PostgreSQL stores microseconds differently, which causes hash mismatches.
            var now = DateTime.UtcNow;
            var timestamp = new DateTime(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second, DateTimeKind.Utc);

            // Convert userId=0 to NULL for consistent hashing
            int? actualUserId = userId == 0 ? null : userId;

            // Hash is computed immediately (before SaveChanges), based only on known data (WITHOUT ID)
            var hash = GenerateHashForData(timestamp, actualUserId, action, entityType, entityId, changes);

            var auditLog = new AuditLog
            {
                Timestamp = timestamp,
                UserId = actualUserId,
                Action = action,
                EntityType = entityType,
                EntityId = entityId,
                Changes = changes,
                IpAddress = ipAddress,
                Hash = hash,
                PreviousHash = null
            };

            _dbContext.AuditLogs.Add(auditLog);
            await _dbContext.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("Tamper-proof Audit Log created: Id={Id}, Action={Action}, Timestamp={Timestamp}, Hash={Hash}",
                auditLog.Id, action, timestamp.ToString("yyyy-MM-dd HH:mm:ss"), hash[..10] + "...");

            return auditLog;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating tamper-proof audit log");
            throw;
        }
    }

    /// <summary>
    /// Verifies the integrity of each individual audit log entry.
    /// Hash is computed WITHOUT the ID (since ID is not part of the hash).
    /// Timestamp is rounded to seconds (no milliseconds).
    /// </summary>
    public async Task<AuditLogVerificationResult> VerifyAuditLogIntegrityAsync(int? limitToLast = null, CancellationToken cancellationToken = default)
    {
        try
        {
            var query = _dbContext.AuditLogs
                .OrderBy(a => a.Id);

            var logs = limitToLast.HasValue
                ? await query.Take(limitToLast.Value).ToListAsync(cancellationToken)
                : await query.ToListAsync(cancellationToken);

            var result = new AuditLogVerificationResult
            {
                TotalChecked = logs.Count,
                IsValid = true
            };

            if (logs.Count == 0)
            {
                _logger.LogInformation("No audit logs to verify");
                return result;
            }

            foreach (var log in logs)
            {
                // Round timestamp to seconds (remove milliseconds)
                var timestamp = new DateTime(log.Timestamp.Year, log.Timestamp.Month, log.Timestamp.Day,
                    log.Timestamp.Hour, log.Timestamp.Minute, log.Timestamp.Second, DateTimeKind.Utc);

                // Compute hash WITHOUT ID (data-only basis)
                var calculatedHash = GenerateHashForData(
                    timestamp,
                    log.UserId,
                    log.Action,
                    log.EntityType,
                    log.EntityId,
                    log.Changes);

                if (log.Hash != calculatedHash)
                {
                    result.IsValid = false;
                    result.InvalidLogs.Add(new InvalidLogEntry
                    {
                        LogId = log.Id,
                        Reason = $"Hash manipuliert! Erwartet: {calculatedHash?[..20]}..., Gefunden: {log.Hash?[..20]}..."
                    });

                    _logger.LogWarning("Hash mismatch for Log {LogId}: Timestamp: {Timestamp}, Stored: {Stored}, Calculated: {Calculated}",
                        log.Id, timestamp.ToString("yyyy-MM-dd HH:mm:ss"), log.Hash?[..20], calculatedHash[..20]);
                }
            }

            if (result.IsValid)
            {
                _logger.LogInformation("Audit log integrity verified: {Count} entries OK", logs.Count);
            }
            else
            {
                _logger.LogWarning("Audit log integrity violated! {InvalidCount} of {TotalCount} entries invalid",
                    result.InvalidLogs.Count, logs.Count);
            }

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error during audit log verification");
            throw;
        }
    }

    /// <summary>
    /// Generates a hash based ONLY on immutable data (WITHOUT the ID).
    /// Timestamp is formatted as "yyyy-MM-dd HH:mm:ss" (WITHOUT milliseconds).
    /// </summary>
    private string GenerateHashForData(
        DateTime timestamp,
        int? userId,
        string action,
        string? entityType,
        int? entityId,
        string? changes)
    {
        // ID is NOT part of the hash.
        // Timestamp only to seconds (no milliseconds).
        // Format: "yyyy-MM-dd HH:mm:ss" (ISO 8601 without milliseconds)
        var timestampStr = timestamp.ToString("yyyy-MM-dd HH:mm:ss");
        var content = $"{timestampStr}|{userId?.ToString() ?? ""}|{action ?? ""}|{entityType ?? ""}|{entityId?.ToString() ?? ""}|{changes ?? ""}";

        return GenerateHash(content);
    }

    private string GenerateHash(string content)
    {
        var bytes = Encoding.UTF8.GetBytes(content);
        var hash = SHA256.HashData(bytes);
        return Convert.ToBase64String(hash);
    }

    /// <summary>
    /// Exports audit logs as JSON for forensic analysis.
    /// </summary>
    public async Task<string> ExportAuditLogsAsync(DateTime? from = null, DateTime? to = null, CancellationToken cancellationToken = default)
    {
        var query = _dbContext.AuditLogs.AsQueryable();

        if (from.HasValue)
            query = query.Where(a => a.Timestamp >= from.Value);

        if (to.HasValue)
            query = query.Where(a => a.Timestamp <= to.Value);

        var logs = await query
            .OrderBy(a => a.Timestamp)
            .ToListAsync(cancellationToken);

        var export = new
        {
            ExportDate = DateTime.UtcNow,
            TotalLogs = logs.Count,
            DateRange = new { From = from, To = to },
            Logs = logs.Select(l => new
            {
                l.Id,
                Timestamp = l.Timestamp.ToString("yyyy-MM-dd HH:mm:ss"),
                l.UserId,
                l.Action,
                l.EntityType,
                l.EntityId,
                l.Changes,
                l.IpAddress,
                l.Hash,
                l.PreviousHash
            })
        };

        return JsonSerializer.Serialize(export, new JsonSerializerOptions
        {
            WriteIndented = true
        });
    }

    /// <summary>
    /// Analyzes a specific audit log and shows hash details for debugging.
    /// </summary>
    public async Task<string> DebugAuditLogHashAsync(int logId, CancellationToken cancellationToken = default)
    {
        try
        {
            var log = await _dbContext.AuditLogs
                .FirstOrDefaultAsync(a => a.Id == logId, cancellationToken);

            if (log == null)
                return $"Log {logId} nicht gefunden";

            // Round timestamp to seconds
            var timestamp = new DateTime(log.Timestamp.Year, log.Timestamp.Month, log.Timestamp.Day,
                log.Timestamp.Hour, log.Timestamp.Minute, log.Timestamp.Second, DateTimeKind.Utc);

            // Compute hash based on current data (WITHOUT ID)
            var calculatedHash = GenerateHashForData(
                timestamp,
                log.UserId,
                log.Action,
                log.EntityType,
                log.EntityId,
                log.Changes);

            var timestampStr = timestamp.ToString("yyyy-MM-dd HH:mm:ss");
            var content = $"{timestampStr}|{log.UserId?.ToString() ?? ""}|{log.Action ?? ""}|{log.EntityType ?? ""}|{log.EntityId?.ToString() ?? ""}|{log.Changes ?? ""}";

            var debug = new
            {
                LogId = log.Id,
                TimestampOriginal = log.Timestamp.ToString("O"),
                TimestampRounded = timestampStr,
                UserId = log.UserId?.ToString() ?? "NULL",
                Action = log.Action ?? "NULL",
                EntityType = log.EntityType ?? "NULL",
                EntityId = log.EntityId?.ToString() ?? "NULL",
                Changes = log.Changes ?? "NULL",
                StoredHash = log.Hash,
                CalculatedHash = calculatedHash,
                HashMatches = log.Hash == calculatedHash,
                Content = content,
                IsValid = log.Hash == calculatedHash ? "VALID" : "TAMPERED"
            };

            return JsonSerializer.Serialize(debug, new JsonSerializerOptions { WriteIndented = true });
        }
        catch (Exception ex)
        {
            return $"Fehler: {ex.Message}";
        }
    }
}

public sealed class AuditLogVerificationResult
{
    public int TotalChecked { get; set; }
    public bool IsValid { get; set; }
    public List<InvalidLogEntry> InvalidLogs { get; set; } = new();
}

public sealed class InvalidLogEntry
{
    public int LogId { get; set; }
    public string Reason { get; set; } = string.Empty;
}
